# Generated by Django 6.0.2 on 2026-04-11 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_start', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='Stories.node')),
                ('next_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stories.node')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stories.story'),
        ),
    ]
